/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/student/attendance`; params?: Router.UnknownInputParams; } | { pathname: `/student/home`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/AttendanceScreen`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/home`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/PhotoUploadScreen`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/ProxyReviewScreen`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/components/BroadcastingModal`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/components/ProxyAlertModal`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/student/attendance`; params?: Router.UnknownOutputParams; } | { pathname: `/student/home`; params?: Router.UnknownOutputParams; } | { pathname: `/teacher/AttendanceScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/teacher/home`; params?: Router.UnknownOutputParams; } | { pathname: `/teacher/PhotoUploadScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/teacher/ProxyReviewScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/teacher/components/BroadcastingModal`; params?: Router.UnknownOutputParams; } | { pathname: `/teacher/components/ProxyAlertModal`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/student/attendance${`?${string}` | `#${string}` | ''}` | `/student/home${`?${string}` | `#${string}` | ''}` | `/teacher/AttendanceScreen${`?${string}` | `#${string}` | ''}` | `/teacher/home${`?${string}` | `#${string}` | ''}` | `/teacher/PhotoUploadScreen${`?${string}` | `#${string}` | ''}` | `/teacher/ProxyReviewScreen${`?${string}` | `#${string}` | ''}` | `/teacher/components/BroadcastingModal${`?${string}` | `#${string}` | ''}` | `/teacher/components/ProxyAlertModal${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/student/attendance`; params?: Router.UnknownInputParams; } | { pathname: `/student/home`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/AttendanceScreen`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/home`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/PhotoUploadScreen`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/ProxyReviewScreen`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/components/BroadcastingModal`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/components/ProxyAlertModal`; params?: Router.UnknownInputParams; };
    }
  }
}
